# Generated by Django 3.0.7 on 2020-06-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureAnnotationSystem', '0002_annotationinfo_annotation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationinfo',
            name='annotation_points',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='annotationinfo',
            name='annotation_text',
            field=models.TextField(null=True),
        ),
    ]
