# Generated by Django 3.0.7 on 2020-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureAnnotationSystem', '0003_auto_20200627_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationinfo',
            name='annotation_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotationinfo',
            name='old_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
