# Generated by Django 3.0.7 on 2020-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureAnnotationSystem', '0006_auto_20200628_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureinfo',
            old_name='pic_user',
            new_name='pic_user_ip',
        ),
        migrations.AddField(
            model_name='pictureinfo',
            name='pic_user_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
